### ISSUE TITLE
How to use this with Picasso?

### ISSUE THREAD

**Issue by Aditya94A** [KartikPrajapati/StackImageView#3]

**Comment by KartikPrajapati** [comment]
You don't have to use any third party library for image loading, you have to just provide list of image urls.

**Comment by Drastaro** [comment]
> You don't have to use any third party library for image loading, you have to just provide list of image urls.

This one is not working, only keeps loading and shows a weird placeholder image.

**Comment by KartikPrajapati** [comment]
Can you please provide more detail i mean logs and all?

**Comment by KartikPrajapati** [comment]
After long time,not getting any response from issuer, so closing this ticket.
If issue persist, open again this ticket.
